export const pestTableData: string[] = [
  "ბუზი",
  "ქინქლა",
  "ტარაკანი",
  "ჭიანჭველა",
  "რწყილი",
  "ბაღლინჯო",
  "თაგვი",
  "ვირთხა",
  "ქვეწარმავალი",
  "ბაქტერია",
  "ბზიკი",
];
export const materialsTableData: string[] = [
  "მხოხავი მავნებლის ფირფიტა",
  "Killzone მღრღ. ფირფიტა",
  "Killzone მწერის ფირფიტა",
  "BROMOBLEU",
  "RATIMOR",
  "Cipex10e",
  "RAPTOR GEL",
  "BLEU DELTA",
  "AGITA",
  "SURFANIOS PREMIUM",
  "REPTIL NATURAL STOP",
  "ALFADOM",
];
